apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apps-tls-staging-cert
spec:
  secretName: apps-tls-staging-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - Maxime
  commonName: maxime-lenne.fr
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - baserow.staging.maxime-lenne.fr
    - n8n.staging.maxime-lenne.fr
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io 