apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: sbs-default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: n8n
        image: n8nio/n8n:latest
        ports:
        - containerPort: 5678
        env:
        - name: DB_TYPE
          value: postgresdb
        - name: DB_POSTGRESDB_HOST
          value: postgresql
        - name: DB_POSTGRESDB_PORT
          value: "5432"
        - name: GENERIC_TIMEZONE
          value: "Europe/Paris"
        - name: DB_POSTGRESDB_DATABASE
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: N8N_DB_NAME
        - name: DB_POSTGRESDB_USER
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: N8N_DB_USER
        - name: DB_POSTGRESDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: N8N_DB_PASSWORD
        - name: N8N_HOST
          value: "${N8N_STAGING_DOMAIN}"
        - name: N8N_PORT
          value: "5678"
        - name: N8N_PROTOCOL
          value: "https"
        - name: N8N_USER_MANAGEMENT_DISABLED
          value: "true"
        - name: N8N_BASIC_AUTH_ACTIVE
          value: "false"
        - name: N8N_DIAGNOSTICS_ENABLED
          value: "false"
        - name: WEBHOOK_URL
          value: "https://${N8N_STAGING_DOMAIN}"
        - name: N8N_HIRING_BANNER_ENABLED
          value: "false"
        - name: N8N_EMAIL_MODE
          value: "smtp"
        - name: N8N_SMTP_HOST
          value: "smtp.gmail.com"
        - name: N8N_SMTP_PORT
          value: "587"
        - name: N8N_SMTP_USER
          value: "your-email@gmail.com"
        - name: N8N_SMTP_PASS
          value: "your-app-password"
        - name: N8N_SMTP_SENDER
          value: "your-email@gmail.com"
        - name: N8N_SMTP_REPLY_TO
          value: "your-email@gmail.com"
        - name: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
          value: "false"
        - name: N8N_RUNNERS_ENABLED
          value: "true"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: n8n-data
          mountPath: /home/node/.n8n
      volumes:
      - name: n8n-data
        persistentVolumeClaim:
          claimName: n8n-data
---
apiVersion: v1
kind: Service
metadata:
  name: n8n
spec:
  selector:
    app: n8n
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
  type: ClusterIP
