apiVersion: v1
kind: Secret
metadata:
  name: secrets-<environnement> # À adapter : secrets-staging, secrets-prod, etc.
  namespace: <environnement>     # À adapter : staging, prod, local...
type: Opaque
stringData:
  # Exemple de clés à adapter selon vos besoins
  BASEROW_SECRET_KEY: "votre_baserow_secret_key"
  BASEROW_JWT_SECRET: "votre_baserow_jwt_secret"
  N8N_DB_PASSWORD: "votre_n8n_db_password"
  REDIS_PASSWORD: "votre_redis_password"
  POSTGRES_PASSWORD: "votre_postgres_password"
  BASEROW_DB_PASSWORD: "votre_baserow_db_password"
# Ce fichier doit être scellé avec kubeseal puis supprimé (ne jamais le commiter en clair !)