apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql-secret
  labels:
    app: postgresql
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.database.user | default .Values.global.secrets.postgresql.username | default "postgres" | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.password | default .Values.global.secrets.postgresql.password | default (randAlphaNum 16) | quote }}
  N8N_DB_NAME: {{ .Values.database.n8n.dbName | default .Values.global.secrets.postgresql.n8n.dbName | default "n8n_db" | quote }}
  N8N_DB_USER: {{ .Values.database.n8n.user | default .Values.global.secrets.postgresql.n8n.username | default "n8n_user" | quote }}
  N8N_DB_PASSWORD: {{ .Values.database.n8n.password | default .Values.global.secrets.postgresql.n8n.password | default (randAlphaNum 16) | quote }}
  BASEROW_DB_NAME: {{ .Values.database.baserow.dbName | default .Values.global.secrets.postgresql.baserow.dbName | default "baserow_db" | quote }}
  BASEROW_DB_USER: {{ .Values.database.baserow.user | default .Values.global.secrets.postgresql.baserow.username | default "baserow_user" | quote }}
  BASEROW_DB_PASSWORD: {{ .Values.database.baserow.password | default .Values.global.secrets.postgresql.baserow.password | default (randAlphaNum 16) | quote }}