# Development environment configuration
global:
  environment: development
  storageClass: sbs-default

  # Ingress configuration
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: selfsigned-issuer
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
      baserow:
        host: baserow.local
        paths:
          - path: /
            pathType: Prefix
      n8n:
        host: n8n.local
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: apps-tls-local-cert
        hosts:
          - baserow.local
          - n8n.local

# Component-specific overrides for development
postgresql:
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"

redis:
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

baserow:
  resources:
    requests:
      memory: "512Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "200m"

n8n:
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"