apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: baserow-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: sbs-default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baserow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baserow
  template:
    metadata:
      labels:
        app: baserow
    spec:
      containers:
      - name: baserow
        image: baserow/baserow:latest
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_TYPE
          value: postgresql
        - name: DATABASE_HOST
          value: postgresql
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: BASEROW_DB_NAME
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: BASEROW_DB_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: BASEROW_DB_PASSWORD
        - name: BASEROW_PUBLIC_URL
          value: https://${BASEROW_PROD_DOMAIN}
        - name: BASEROW_BACKEND_URL
          value: https://${BASEROW_PROD_DOMAIN}
        - name: BASEROW_FRONTEND_URL
          value: https://${BASEROW_PROD_DOMAIN}
        - name: DJANGO_SETTINGS_MODULE
          value: baserow.config.settings.base
        - name: WEBFRONTEND_URL
          value: https://${BASEROW_PROD_DOMAIN}
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: REDIS_PASSWORD
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: baserow-secret
              key: SECRET_KEY
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: baserow-secret
              key: JWT_SECRET
        volumeMounts:
        - name: baserow-data
          mountPath: /baserow/data
        resources:
          requests:
            memory: "2Gi"
            cpu: "250m"
          limits:
            memory: "4Gi"
            cpu: "500m"
      volumes:
      - name: baserow-data
        persistentVolumeClaim:
          claimName: baserow-data
