apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apps-tls-prod-cert
spec:
  secretName: apps-tls-prod-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - Maxime
  commonName: ${PROD_DOMAIN}
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - ${BASEROW_PROD_DOMAIN}
    - ${N8N_PROD_DOMAIN}
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io 