apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apps-tls-prod-cert
  namespace: prod
spec:
  secretName: apps-tls-prod-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - Maxime
  commonName:
    valueFrom:
      configMapKeyRef:
        name: app-config-prod
        key: PROD_DOMAIN
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - valueFrom:
        configMapKeyRef:
          name: app-config-prod
          key: BASEROW_PROD_DOMAIN
    - valueFrom:
        configMapKeyRef:
          name: app-config-prod
          key: N8N_PROD_DOMAIN
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io 