apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-redis-secret
  labels:
    app: redis
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  REDIS_PASSWORD: {{ .Values.password | default .Values.global.secrets.redis.password | default (randAlphaNum 16) | quote }}