---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: excalidraw-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: sbs-default
