# base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Baserow
  - baserow/baserow-deployment.yaml
  - baserow/baserow-secret.yaml
  - baserow/baserow-service.yaml
  - baserow/baserow-pvc.yaml

  # N8N
  - n8n/n8n-deployment.yaml
  - n8n/n8n-pvc.yaml
  - n8n/n8n-service.yaml

  # PostgreSQL
  - postgresql/postgresql-secret.yaml
  - postgresql/postgresql-pvc.yaml
  - postgresql/postgresql-deployment.yaml
  - postgresql/postgresql-service.yaml

  # PostgreSQL Database Initialization
  - postgresql/init-script-configmap.yaml

  # Redis
  - redis/redis-secret.yaml
  - redis/redis-deployment.yaml
  - redis/redis-service.yaml

  # Ingress Nginx Configuration
  - ingress-nginx/ingress-nginx-configmap.yaml

  # Application Ingress (Baserow & N8N)
  - apps-ingress.yaml

  # Cert-Manager Issuers
  - cert-managers/letsencrypt-issuer.yaml
  - cert-managers/self-signed-issuer.yaml
