apiVersion: v1
kind: ConfigMap
metadata:
  name: init-script
data:
  init-database.sh: |
    #!/bin/bash
    set -e
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        CREATE DATABASE n8n_db;
        CREATE USER n8n_user WITH PASSWORD '$N8N_DB_PASSWORD';
        GRANT ALL PRIVILEGES ON DATABASE n8n_db TO n8n_user;
        ALTER DATABASE n8n_db OWNER TO n8n_user;
        CREATE DATABASE baserow_db;
        CREATE USER baserow_user WITH PASSWORD '$BASEROW_DB_PASSWORD';
        GRANT ALL PRIVILEGES ON DATABASE baserow_db TO baserow_user;
        ALTER DATABASE baserow_db OWNER TO baserow_user;
    EOSQL