---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-gotrue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supabase-gotrue
  template:
    metadata:
      labels:
        app: supabase-gotrue
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command:
            - 'sh'
            - '-c'
            - >
              until nc -z postgresql 5432;
              do
                echo waiting for postgres;
                sleep 2;
              done;
      containers:
        - name: gotrue
          image: supabase/gotrue:v2.99.0
          ports:
            - containerPort: 9999
          env:
            - name: GOTRUE_API_HOST
              value: "0.0.0.0"
            - name: GOTRUE_API_PORT
              value: "9999"
            - name: GOTRUE_DB_DRIVER
              value: "postgres"
            - name: GOTRUE_DB_HOST
              value: postgresql
            - name: GOTRUE_DB_PORT
              value: "5432"
            - name: GOTRUE_DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: SUPABASE_DB_USER
            - name: GOTRUE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: SUPABASE_DB_PASSWORD
            - name: GOTRUE_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: SUPABASE_DB_NAME
            - name: GOTRUE_DB_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: SUPABASE_DB_URI
            - name: GOTRUE_SITE_URL
              value: "http://localhost:3000"
            - name: API_EXTERNAL_URL
              value: "http://localhost:3000"
            - name: GOTRUE_URI_ALLOW_LIST
              value: "*"
            - name: GOTRUE_DISABLE_SIGNUP
              value: "false"
            - name: GOTRUE_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: JWT_SECRET
            - name: GOTRUE_JWT_EXP
              value: "3600"
            - name: GOTRUE_JWT_DEFAULT_GROUP_NAME
              value: "authenticated"
            - name: GOTRUE_EXTERNAL_EMAIL_ENABLED
              value: "true"
            - name: GOTRUE_MAILER_AUTOCONFIRM
              value: "true"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
