---
apiVersion: v1
kind: Service
metadata:
  name: supabase-gotrue
  labels:
    app: supabase-gotrue
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9999
      targetPort: 9999
      protocol: TCP
  selector:
    app: supabase-gotrue
