---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supabase-kong
  template:
    metadata:
      labels:
        app: supabase-kong
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command:
            - 'sh'
            - '-c'
            - >
              until nc -z postgresql 5432;
              do
                echo waiting for postgres;
                sleep 2;
              done;
      containers:
        - name: kong
          image: kong/kong-gateway:2.8.1.0-alpine
          ports:
            - containerPort: 8000
            - containerPort: 8443
          env:
            - name: KONG_DATABASE
              value: "postgres"
            - name: KONG_PG_HOST
              value: postgresql
            - name: KONG_PG_PORT
              value: "5432"
            - name: KONG_PG_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: SUPABASE_DB_NAME
            - name: KONG_PG_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: SUPABASE_DB_USER
            - name: KONG_PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: SUPABASE_DB_PASSWORD
            - name: KONG_PG_SSL
              value: "off"
            - name: KONG_PROXY_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_ADMIN_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_PROXY_ERROR_LOG
              value: /dev/stderr
            - name: KONG_ADMIN_ERROR_LOG
              value: /dev/stderr
            - name: KONG_ADMIN_LISTEN
              value: "0.0.0.0:8001"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
